name: Bug Report
description: Create a report to help us improve
labels: []
body: 
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Thank you for your bug report.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected nu to...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add any relevant screenshots here, if any
    validations:
      required: false
  - type: textarea
    id: shell
    attributes:
      label: Shell
      description: What shell is the bug occurring on?
      placeholder: |
        # For bash, run `bash --version | head -n 1` and paste the output
        GNU bash, version 5.2.15(2)-release (x86_64-pc-linux-gnu)

        # For zsh, run `zsh --version` and paste the output
        zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

        # For powershell, run `$PSVersionTable` and paste the output
        Name                           Value
        ----                           -----
        PSVersion                      7.4.0
        PSEdition                      Core
        GitCommitId                    7.4.0
        OS                             Microsoft Windows 10.0.19045
        Platform                       Win32NT
        PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
        PSRemotingProtocolVersion      2.3
        SerializationVersion           1.1.0.1
        WSManStackVersion              3.0

        # For fish, run `fish --version` and paste the output
        fish, version 3.6.1

        # For nushell, run `nu --version` and paste the output
        0.86.0

        # For elvish, run `elivsh --version` and paste the output
        0.19.2+official

        # For xonsh, run `xonsh --version` and paste the output
        xonsh/0.14.0

        # For xonsh, run `tcsh --version` and paste the output
        tcsh 6.24.00 (Astron) 2022-02-02 (x86_64-unknown-linux) options wide,nls,dl,al,kan,sm,rh,color,filec
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: Please run `argc version` and paste the output
      placeholder: |
        argc-completions 30f7d9a
        argc 1.14.0
        yq (https://github.com/mikefarah/yq/) version v4.40.3
        GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)
        sed (GNU sed) 4.8
        Linux nix 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
